### ISSUE TITLE
CustomForwardTeam team is not forward!

### ISSUE THREAD

**Issue by joaopedrovbs** [ivanseidel/Robot-Soccer-Simulator#5]
The custom forward team is actually going diagonally, as seen in the code below, this is unacceptable...

```
setSpeed(0.5f,0.028f);
delay(100);
```

Please fix this!

**Comment by ivanseidel** [comment]
That depends on what you call "front" of the robot. Relative to it's diagonal, it's Forward.

**Comment by joaopedrovbs** [comment]
So why is that line there? Just to show the robot's non-position? This is still unacceptable!
